# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160618_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='f_test_e',
            field=models.IntegerField(verbose_name=b'end index of final test'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='mid_test_e',
            field=models.IntegerField(verbose_name=b'end index of mid test'),
        ),
    ]
