# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 06:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160618_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 18, 6, 26, 0, 800000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
