# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_competition_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='contest_type',
            field=models.CharField(choices=[('REG', b'regression'), ('CLF', b'classification'), ('CLS', b'clustering')], default=b'regression', max_length=10, verbose_name=b'contest type'),
        ),
    ]
