# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_competition_contest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=255, verbose_name=b'competition name'),
        ),
    ]
