# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160618_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='short_comment',
            field=models.CharField(default=1, max_length=255, verbose_name=b'Short Comment'),
            preserve_default=False,
        ),
    ]
