# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_submission_short_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='short_comment',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Short Comment'),
        ),
    ]
