# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160618_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='competition_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='app.Competition', verbose_name=b'Competition name'),
        ),
    ]
