# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_competition_data_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='f_result',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name=b'final result'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='mid_result',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name=b'mid result'),
        ),
    ]
