# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20160618_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='contest_type',
            field=models.CharField(choices=[('Regression', b'regression'), ('Classification', b'classification'), ('Clustering', b'clustering')], default=b'regression', max_length=20, verbose_name=b'contest type'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='scoring',
            field=models.CharField(choices=[('MSE', 'MSE'), ('RMSE', 'RMSE'), ('Correlation', 'CORRELATION'), ('Accuracy', 'ACCURACY'), ('F1', 'F1'), ('Adjusted Rand Score', 'ADJUSTED RAND SCORE')], default=b'RMSE', max_length=20, verbose_name=b'scoring method'),
        ),
    ]
