# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.AddField(
            model_name='competition',
            name='max_submission',
            field=models.IntegerField(default=2, verbose_name=b'Max submission per day'),
        ),
    ]
