# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160619_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_expired',
            field=models.IntegerField(default=0, verbose_name=b'is_expired'),
        ),
    ]
