# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_submission_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name=b'competition name'),
        ),
    ]
